### ISSUE TITLE
您好 请问能否添加托盘图标?

### ISSUE THREAD

**Issue by GH-Ryan** [changbowen/DesktopNote#10]
1. 在 Windows 下按 `Win + D` 回到桌面时便签也不见了,虽然再次按下 `Win + D` 可以恢复,但是其他窗口也会恢复.这样很不方便.
能否添加托盘图标呢? 这样双击就可以找到便签了.
2. 另外,如果不是以管理员身份运行会读取不到便笺,发生载入错误.
3.便签在桌面边缘自动隐藏后,鼠标反复移入移出几次,便签就停在桌面不会自动隐藏了.
4.谢谢您的软件

**Comment by changbowen** [comment]
1 => 试一下最新版。
2 => 默认笔记内容保存到程序exe的根目录下，是不是没有根目录的访问权限？
3 => 在弹出动画结束前鼠标如果移出了笔记窗口，不会自动隐藏。如果输入焦点在笔记窗口内，也不会自动隐藏。

**Comment by changbowen** [comment]
assume fixed
