### ISSUE TITLE
设置界面显示不全

### ISSUE THREAD

**Issue by Using1174** [changbowen/DesktopNote#14]
![image](https://user-images.githubusercontent.com/16488261/38910622-c2983802-42fc-11e8-8546-a54a25f585dc.png)

**Comment by changbowen** [comment]
.net是什么版本？尝试更新到4.5+试试？
我这边是没问题的

**Comment by changbowen** [comment]
有一部分类和属性是4.5才有的。改target framework需要改代码，而且不一定是.net的问题。
目前没有太多时间来改代码，不好意思。。
