### ISSUE TITLE
How can I insert a picture?

### ISSUE THREAD

**Issue by CN-Ironegg** [changbowen/DesktopNote#19]
我翻遍了右键菜单，也尝试复制图片再粘贴，但是仍然无法**插入图片**
How can I insert a picture?I went through the right-click menu and tried to copy the image and paste it again, but I still couldn't insert the image😟 
希望能解决

**Comment by changbowen** [comment]
Inserting image is done by pasting the bitmap data. The clipboard will contain bitmap data if you press the Print Screen key or use a snipping tool.
It does not work if you copy and paste the image file (i.e. by pressing Ctrl+C on the image file then Ctrl+V in the note window).

Inserting images was not a priority back then and the possibility to insert images was built-in to the `RichTextBox` control (if I remember correctly).

Hope this answers the question!

**Comment by CN-Ironegg** [comment]
Thank you for your reply, I will try the solution until the problem is solved.

**Comment by CN-Ironegg** [comment]
建议加入一个拖进窗口插入图片的功能，这将会对触屏win设备有莫大帮助

**Comment by changbowen** [comment]
Currently I don't have the time or access to a proper touch device for this but pull requests are always welcome :)

**Comment by CN-Ironegg** [comment]
OK, thank you for your reply. By the way, it is not necessary to debug on the touch device to achieve touch device compatibility.
（_Sorry for my poor of English_ (ｐ・・q））

**Comment by changbowen** [comment]
Fixed in commit https://github.com/changbowen/DesktopNote/commit/ce7e631c593d98e79384dc4bc7fbaa5bb7bb2a66 and https://github.com/changbowen/DesktopNote/commit/a957135b369a0320689d0a4df507669e680f4a99
