### ISSUE TITLE
Custom project reset issue

### ISSUE THREAD

**Issue by homjie** [changbowen/DesktopNote#20]
The background color、 font and font color need to be reset each time. Could you please develop: save the custom color scheme  and  Remember the last font setting

**Comment by changbowen** [comment]
The beauty of open source is that anyone can contribute freely. Open source does not imply responsibility, support or free lifetime updates.
And giving ideas without execution is not contribution.
With that said, if you feel something can be improved, put in a PR and I'm happy to look at it.
